#!/usr/bin/env node
/*! @license ©2014 Ruben Verborgh - Multimedia Lab / iMinds / Ghent University */
/* Builds the query files into a JSON file. */

var fs = require('fs');

var outputFile = __dirname + '/queries.json',
    queryDir = __dirname + '/queries/',
    queryFiles = fs.readdirSync(queryDir)
                   .filter(function (f) { return /\.sparql$/.test(f); });

// Create queries for each of the query files
var queries = queryFiles.map(function (queryFile) {
  var query = fs.readFileSync(queryDir + queryFile, { encoding: 'utf8' }),
      key = queryFile.replace(/\.\w+$/, '');

  // Try to extract the name for the query from a comment line
  var lines = query.split('\n'), firstLine = lines.shift() || '';
  if (firstLine[0] === '#') {
    key = firstLine.replace(/#\s*/, '');
    query = lines.join('\n');
  }

  return { name: key, sparql: query };
});

fs.writeFileSync(outputFile, JSON.stringify(queries));
