# Publications by Anne De Paepe
# Datasource: http://data.linkeddatafragments.org/ugent-biblio
SELECT ?title ?classification WHERE {
  ?author foaf:name "Anne De Paepe".
  ?publication dc:creator ?author;
               dc:title ?title;
               <http://lib.ugent.be/classification/classification> ?classification.
}
