# Ancient cities with a population larger than 50.000
# Datasource: http://fragments.dbpedia.org/2014/en
SELECT * WHERE {
  ?city rdf:type <http://dbpedia.org/class/yago/AncientCities>;
        dbpedia-owl:populationTotal ?popTotal.
  OPTIONAL { ?city dbpedia-owl:populationMetro ?popMetro. }
  FILTER (?popTotal > 50000)
}
ORDER BY DESC(?popTotal)
