# Airports in Italy
# Datasource: http://fragments.dbpedia.org/2014/en
# Datasource: http://fragments.dbpedia.org/2015/en
SELECT DISTINCT ?entity WHERE {
  ?entity a dbpedia-owl:Airport;
          dbpprop:cityServed dbpedia:Italy.
}
