# 1. Directors of movies starring Brad Pitt
# Datasource: http://fragments.dbpedia.org/2014/en
# Datasource: http://fragments.dbpedia.org/2015/en
SELECT ?movie ?title ?name
WHERE {
  ?movie dbpedia-owl:starring [ rdfs:label "Brad Pitt"@en ];
         rdfs:label ?title;
         dbpedia-owl:director [ rdfs:label ?name ].
  FILTER LANGMATCHES(LANG(?title), "EN")
  FILTER LANGMATCHES(LANG(?name),  "EN")
}
