# Death causes of male American actors
# Datasource: http://fragments.dbpedia.org/*/en
PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
SELECT ?actor ?cause
WHERE {
  ?actor dbpedia-owl:deathCause ?cause.
  ?actor dc:subject <http://dbpedia.org/resource/Category:American_male_film_actors>
}
