# Desserts made with plants
# Datasource: http://fragments.dbpedia.org/2014/en
# Datasource: http://fragments.dbpedia.org/2015/en
SELECT ?dessert ?fruit
WHERE {
  ?dessert dbpedia-owl:type <http://dbpedia.org/resource/Dessert>;
           dbpedia-owl:ingredient ?fruit.
  ?fruit dbpedia-owl:kingdom <http://dbpedia.org/resource/Plant>.
}
