# Events that took place in the Trentino region
# Datasource: http://fragments.dbpedia.org/*/en
SELECT DISTINCT ?entity ?event
WHERE {
  ?entity a dbpedia-owl:Event;
          rdfs:label ?event;
          ?predicate <http://dbpedia.org/resource/Trentino> .
  FILTER(langMatches(lang(?event), "EN"))
}
