# Foreign titles of Natalie Portman movies
# Datasource: http://fragments.dbpedia.org/*/en
SELECT ?titleEng ?title
WHERE {
    ?movie dbpprop:starring [ rdfs:label "Natalie Portman"@en ];
           rdfs:label ?titleEng, ?title.
    FILTER LANGMATCHES(LANG(?titleEng), "EN")
    FILTER (!LANGMATCHES(LANG(?title), "EN"))
}
