# Artists influenced by Picasso
# Datasource: http://fragments.dbpedia.org/2014/en
# Datasource: http://fragments.dbpedia.org/2015/en
CONSTRUCT {
  ?artist a dbpedia-owl:Artist.
  ?artist dbpedia-owl:birthDate ?date.
}
WHERE {
  ?artist dbpedia-owl:influencedBy dbpedia:Pablo_Picasso.
  ?artist a dbpedia-owl:Artist.
  ?artist dbpedia-owl:birthDate ?date.
}
