# Publications by Thomson and Thompson
# Datasource: http://data.linkeddatafragments.org/ugent-biblio
SELECT ?jansen ?janssen ?title {
  ?publication dc:creator [ foaf:givenname ?jansen;  foaf:surname "Jansen" ];
               dc:creator [ foaf:givenname ?janssen; foaf:surname "Janssen" ];
               dc:title ?title.
}
